pie
  title Funding Sources (Extended Portfolio)
  "Core institutional funding" : 35
  "Internal projects & services" : 15
  "National research grants" : 20
  "EU framework projects" : 15
  "Industry contracts" : 8
  "Membership fees" : 4
  "Donations & sponsorships" : 2
  "Other" : 1
